### ISSUE TITLE
Feature request: add INI__ALL_SECTIONS to hold all section name

### ISSUE THREAD

**Issue by machixian** [rudimeier/bash_ini_parser#3]
Add INI__ALL_SECTIONS can be used in such satution:
Say I want to backup a list of mysql databases, and each of them have a different username and password, and the list of databases can be grow in the future, so I configure all databases in a ini file like this:

```
[db01]
name=db-host01
username=user1
password=pwd01

[db02]
name=db-host2
username=user2
password=pwd2
```

And in the backup script I can use some thing like 

```
for db in `echo INI__ALL_SECTIONS`; do 
  name="INI__${db}__name"
  echo "username of $db is ${!name}"
done
```

So everytime I need add a new database for backup, I only need to add a section in the ini file without change the backup sctipt.

**Comment by rudimeier** [comment]
Thanks, I've merged your changings into my master branch.

**Comment by machixian** [comment]
Hi @rudimeier, Thanks for the merge.
