### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [rudimeier/bash_ini_parser#7]
I want use bash_ini_parser on Embedded Distribution, so What's License of these?

**Comment by bsdkurt** [comment]
This code is closed source in the current way it is provided. It needs a license for anyone to use it. Please consider adding the ISC license to it (http://en.wikipedia.org/wiki/ISC_license). The ISC license is the most permissive open source license out there.

**Comment by rudimeier** [comment]
Sorry for ignoring this issue.
I have added a BSD-3-Clause LICENSE file (8fb95e3b) and tagged version 0.4.2.

**Comment by ghost** [comment]
Thank you for apply license!
